name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Root project dependencies and checks
      - name: Install root dependencies
        run: npm ci
      
      - name: Lint root project
        run: npm run lint
      
      - name: Format check root project
        run: npx biome check .
      
      # Vue app dependencies and checks
      - name: Install Vue app dependencies
        working-directory: ./vue-app
        run: npm ci
    
      - name: Type check Vue app
        working-directory: ./vue-app
        run: npm run types
      
      # React app dependencies and checks
      - name: Install React app dependencies
        working-directory: ./react-app
        run: npm i --legacy-peer-deps --force
        
      # Add missing dependency for React tests
      - name: Install missing testing-library/dom dependency
        working-directory: ./react-app
        run: npm install --save-dev @testing-library/dom

      - name: Type check React app
        working-directory: ./react-app
        run: npm run types
      
      # Run all tests from the root directory
      - name: Run all tests
        run: npm test