name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Root project dependencies and checks
      - name: Install root dependencies
        run: npm ci
        working-directory: .
      
      - name: Lint root project
        run: npm run lint
        working-directory: .
      
      - name: Format check root project
        run: npx biome check .
        working-directory: .
      
      # Vue app dependencies and checks
      - name: Install Vue app dependencies
        run: npm ci
        working-directory: ./vue-app
    
      - name: Type check Vue app
        run: npm run types
        working-directory: ./vue-app
      
      # React app dependencies and checks
      - name: Install React app dependencies
        run: npm install --legacy-peer-deps --force
        working-directory: ./react-app

      - name: Type check React app
        run: npm run types
        working-directory: ./react-app
      
      # Run tests from root
      - name: Run tests
        run: npm test
        working-directory: .