name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Format check
      run: |
        npx biome check --write .
        npx biome format --check .
    
    - name: Type check React app
      run: cd react-app && npx tsc -p tsconfig.app.json
      
    - name: Type check Vue app
      run: cd vue-app && npx vue-tsc -p tsconfig.app.json
    
    - name: Run tests
      run: npm test